# Define the root directory for artifacts
artifacts_root: artifacts


# Configuration for data ingestion
data_ingestion:
 
  root_dir: artifacts/data_ingestion # Set the root directory for data ingestion under artifacts
  source_URL: https://github.com/Karnsinh96/Datasets/raw/main/WineQuality-data.zip # Specify the source URL for the data (winequality-data.zip)
  local_data_file: artifacts/data_ingestion/data.zip # Local file path where the downloaded data (ZIP file) will be stored
  unzip_dir: artifacts/data_ingestion # Directory where the contents of the ZIP file will be extracted


# Configuration for data vaidation
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

#Configuration Data Transformation
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

#Configuration for Model Training
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  

#Configuration for Model Evalution
model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json